url: http://yinyunqiao.github.io
title: random thoughts
author: Yunqiao Yin
date_format: "ordinal"
subscribe_rss: /atom.xml
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

default_asides: [asides/recent_posts.html]

# Disqus Comments
disqus_short_name: mazymind
disqus_show_comment_count: true

# Facebook Like
facebook_like: true
